### ユーザー登録の処理
POST http://localhost:10001/api/v1/signup
Content-Type: application/json

{
  "name": "テストユーザー",
  "email": "nagamatsu-k@dym.jp",
  "password": "password",
  "company_id": 1
}


### ログインの処理
POST http://localhost:10001/api/v1/login
Content-Type: application/json

{
  "email": "nagamatsu-k@dym.jp",
  "password": "password"
}
